# Generated by Django 2.0.4 on 2018-06-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='modelo',
            new_name='model',
        ),
    ]
