# Generated by Django 2.0.4 on 2018-06-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_auto_20180623_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(help_text='Ingrese color del auto', max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(help_text='Ingrese modelo del auto', max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='patent',
            field=models.CharField(help_text='Ingrese patente del auto', max_length=6),
        ),
    ]
