# Generated by Django 2.0.4 on 2018-06-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0004_auto_20180623_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='restriction',
        ),
    ]
