# Generated by Django 2.0.4 on 2018-06-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_remove_car_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
