# Generated by Django 2.0.4 on 2018-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('D', 'Disponible'), ('E', 'Entregado'), ('A', 'Arrendado'), ('C', 'Cancelado')], default=None, max_length=60),
            preserve_default=False,
        ),
    ]
