# Generated by Django 2.0.4 on 2018-06-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0008_auto_20180625_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('E', 'Entregado'), ('C', 'Cancelado'), ('A', 'Arrendado')], default='A', max_length=60),
        ),
    ]
